variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_2_FULL.zip'
  WindowsRTCSDKX64: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x64)_v3_0_0_2_FULL.zip'
jobs:

  - template: cicd/templates/build-android.yml
    parameters:
      displayName: 'AndroidOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-Android'

  - template: cicd/templates/build-android.yml
    parameters:
      displayName: 'AndroidTutorial'
      workingDirectory: 'One-to-One-Video/Agora-Android-Tutorial-1to1'

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSSwiftTutorial'
      workingDirectory: 'One-to-One-Video/Agora-iOS-Tutorial-Swift-1to1'
      scheme: 'Agora-iOS-Tutorial'
      sdkurl: $(iOSRTCSDK)
  
  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSOCTutorial'
      workingDirectory: 'One-to-One-Video/Agora-iOS-Tutorial-Objective-C-1to1'
      scheme: 'Agora-iOS-Tutorial-Objective-C'
      sdkurl: $(iOSRTCSDK)

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSSwiftUITutorial'
      workingDirectory: 'One-to-One-Video/Agora-iOS-Tutorial-SwiftUI-1to1'
      scheme: 'Agora-iOS-Tutorial-SwiftUI-1to1'
      sdkurl: $(iOSRTCSDK)

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSSwiftOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-iOS'
      scheme: 'OpenVideoCall'
      sdkurl: $(iOSRTCSDK)

  - template: cicd/templates/build-ios.yml
    parameters:
      displayName: 'iOSOCOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-iOS-Objective-C'
      scheme: 'OpenVideoCall'
      sdkurl: $(iOSRTCSDK)

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacSwiftTutorial'
      workingDirectory: 'One-to-One-Video/Agora-macOS-Tutorial-Swift-1to1'
      scheme: 'Agora-Mac-Tutorial-Swift'
      sdkurl: $(MacRTCSDK)

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacOCTutorial'
      workingDirectory: 'One-to-One-Video/Agora-macOS-Tutorial-Objective-C-1to1'
      scheme: 'Agora-Mac-Tutorial-Objective-C'
      sdkurl: $(MacRTCSDK)

  - template: cicd/templates/build-mac.yml
    parameters:
      displayName: 'MacOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-macOS'
      scheme: 'OpenVideoCall'
      sdkurl: $(MacRTCSDK)

#Windows demo
  - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsTutorial'
      workingDirectory: 'One-to-One-Video/Agora-Windows-Tutorial-1to1'
      scheme: 'Agora-Windows-Tutorial-1to1'
      sdkurl: $(WindowsRTCSDK)
      solutionName: 'AgoraTutorial.sln'
      sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
      Machine: 'win32'
      ReleasePath: 'Release'
  - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsTutorial64'
      workingDirectory: 'One-to-One-Video/Agora-Windows-Tutorial-1to1'
      scheme: 'Agora-Windows-Tutorial-1to1'
      sdkurl: $(WindowsRTCSDKX64)
      solutionName: 'AgoraTutorial.sln'
      sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
      Machine: 'x64'
      ReleasePath: 'x64/Release'
#Group Video
  - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsOpenVideoCallMFC'
      workingDirectory: 'Group-Video/OpenVideoCall-Windows'
      scheme: 'OpenVideoCall-Windows-MFC'
      sdkurl: $(WindowsRTCSDK)
      solutionName: 'OpenVideoCall.sln'
      sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
      Machine: 'win32'
      ReleasePath: 'Release'

  - template: cicd/templates/build-Windows.yml
    parameters:
      displayName: 'WindowsOpenVideoCallMFC64'
      workingDirectory: 'Group-Video/OpenVideoCall-Windows-MFC'
      scheme: 'OpenVideoCall-Windows'
      sdkurl: $(WindowsRTCSDK)
      solutionName: 'OpenVideoCall.sln'
      sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'
      Machine: 'x64'
      ReleasePath: 'x64/Release'
  - template: cicd/templates/build-Windows.yml 